### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 58: illegal multibyte sequence

### ISSUE THREAD

**Issue by Tonynovtop** [nyalldawson/slyr#129]
Hello,
I got an UnicodeDecodeError error when i use the 'Convert Esri style to QGIS style xml' of SLYR in QGIS.
the detial information of error is:
2022-04-13T19:47:46     WARNING    Traceback (most recent call last):
              File "D:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 241, in executeAlgorithm
              ok, message = alg.canExecute()
              File "C:\Users/yiwuz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr_community\qgis_plugin\algorithms\style_to_gpl.py", line 81, in canExecute
              if not Extractor.is_mdb_tools_binary_available():
              File "C:\Users/yiwuz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr_community\bintools\extractor.py", line 149, in is_mdb_tools_binary_available
              for line in proc.stdout:
             UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 58: illegal multibyte sequence
			 

QGIS veriosn: 3.16.16
Python:3.9
Platform:windows 10
mdbtools:https://github.com/lsgunth/mdbtools-win
SLYR: installed from QGIS plugin.
I have set 'Settings -> Options -> SLYR -> set-MDB-tools-path'.

![image](https://user-images.githubusercontent.com/41135574/163179572-e4ea7390-d9e8-4f5b-a1b2-9295ce4cb40d.png)

**Comment by nyalldawson** [comment]
Can you share the document you are trying to convert?

**Comment by Tonynovtop** [comment]
@nyalldawson of course,here is the file link: https://anonfiles.com/J8qbz7Wbx5/test_style,but i think the source of the problem is not in this ducument，because the error happened before i enter the process panel  of "Convert ESRI  style to QGIS style xml".

**Comment by nyalldawson** [comment]
OK, this one is working fine in the licensed SLYR version, so you'll need to wait for the next drop of functionality from the licensed to community version to land.

**Comment by Tonynovtop** [comment]
OK,thank you for your reply.

**Comment by Legebriand** [comment]
[https://github.com/nyalldawson/slyr/issues/98](url)try this
