### ISSUE TITLE
can not use “convert ESRI style to QGIS stye XML"

### ISSUE THREAD

**Issue by smlie2020** [nyalldawson/slyr#130]
When I double-click the tool,An error message appears
Python error: An error has occurred while executing Python code: See message log (Python Error) for more details.
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 58: illegal multibyte sequence 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 241, in executeAlgorithm
    ok, message = alg.canExecute()
  File "C:\Users/**/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr_community\qgis_plugin\algorithms\style_to_xml.py", line 108, in canExecute
    if not Extractor.is_mdb_tools_binary_available():
  File "C:\Users/**/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\slyr_community\bintools\extractor.py", line 149, in is_mdb_tools_binary_available
    for line in proc.stdout:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 58: illegal multibyte sequence


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.6-Białowieża Białowieża, b6f33b1a 

Python Path:
C:\Users/**/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:/PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python
C:/Users/**/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/**/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.6\bin\python39.zip
C:\PROGRA~1\QGIS32~1.6\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib
C:\Program Files\QGIS 3.22.6\bin
C:\PROGRA~1\QGIS32~1.6\apps\Python39
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\Pythonwin
C:/Users/**/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\**\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\**\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
```

**Comment by nyalldawson** [comment]
@smlie2020 can you share the file you are trying to convert?

**Comment by smlie2020** [comment]
The tool cannot be opened and the operation interface cannot pop up. It should have nothing to do with the file to be converted. I can send an email if necessary

**Comment by liuxsdev** [comment]
I think the reason for the error may be the use of "GBK" to decode "\xe2\x80\xaa"

run  `.\mdb-export.exe` in windows，it has a unrecognized character:

![image](https://user-images.githubusercontent.com/11004456/168506347-246fc0bc-733d-4a38-b89e-2cc431fce1ca.png)

I found in mdbtool's  [source code ](https://github.com/mdbtools/mdbtools/blob/49ee8272ab27ffe63269fdd34c9938b13083d151/src/libmdb/fakeglib.c)

![image](https://user-images.githubusercontent.com/11004456/168506533-7866f3d5-f451-40c1-a2d7-68839f24426f.png)

python can not decode "\xe2\x80\xaa" in gbk:

![image](https://user-images.githubusercontent.com/11004456/168506643-5b5185c0-a9b3-4597-9984-db7e313309a1.png)

remove `**Extractor.get_process_keywords()` , operation interface can pop up , But I didn't try to convert any file
![image](https://user-images.githubusercontent.com/11004456/168507771-049c9192-d984-4fa8-aa5c-5d45423070d6.png)

I don't know how to fix it correctly 😣
hope this  will help you fix this problem  @nyalldawson

**Comment by smlie2020** [comment]
Thank you very much, glad to find the reason, but I don't compile the source code, which is beyond my ability.

**Comment by smlie2020** [comment]
I learned that python can't decode "GBK", "GBK" is not the latest Chinese character encoding specification.can try "GB18030", or use "UTF-8", but I don't know how to modify the code

**Comment by JagnDC** [comment]
I think it can simply solve the problem.
![49325d8d997c633b9b6c2bda8d63a30](https://user-images.githubusercontent.com/20790537/182564321-f1aa1058-23c2-428f-8099-1c182675bc14.png)
Just change it, and it works.

**Comment by JagnDC** [comment]
now it works on win10.
![image](https://user-images.githubusercontent.com/20790537/182564987-57ace125-d271-46aa-b0cb-f050087bfed5.png)

**Comment by smlie2020** [comment]
> now it works on win10. ![image](https://user-images.githubusercontent.com/20790537/182564987-57ace125-d271-46aa-b0cb-f050087bfed5.png)
Can you convert the file to give it a try？I also tried to modify, I can open the interface normally, but I can't convert it

**Comment by JagnDC** [comment]
> 
Of course it's fine. 
![image](https://user-images.githubusercontent.com/20790537/183322059-7d9b9fef-6816-43ba-b889-e9423da9e6a7.png)
![image](https://user-images.githubusercontent.com/20790537/183322157-607915d5-ba64-4c67-903a-9c999a33f02c.png)
![image](https://user-images.githubusercontent.com/20790537/183322189-5a6855c6-ed88-4377-b76d-a9c1eba85f02.png)
