### ISSUE TITLE
Conversion Esri style to xml in Ubuntu 18.04

### ISSUE THREAD

**Issue by JCCabreraMX** [nyalldawson/slyr#94]
I'm trying to convert Esri Style to QGIS xml in Ubuntu 18.04 but I get these errors:

1. raise ValueError("creationflags is only supported on Windows "
ValueError: creationflags is only supported on Windows platforms

2. FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/home/jc_cabrera/mdb-export': '/home/jc_cabrera/mdb-export'

What could I'm doing wrong??

**Comment by nyalldawson** [comment]
> raise ValueError("creationflags is only supported on Windows "

Do you have the full stack trace for this one?

> FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/home/jc_cabrera/mdb-export': '/home/jc_cabrera/mdb-export'

You're missing the mdbtools dependancy - try `sudo apt-get install mdbtools`

**Comment by jonasViehweger** [comment]
I'm getting what seems to be the same error on MacOS 10.14.5
mdbtools and all dependencies were installed via homebrew.
Running Python version 3.6.8
I'm trying to convert with the Plug-In in QGIS 3.4.9

Here's the entire stack trace, hope that helps:

Traceback (most recent call last):
File "/Users/grasprak287/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/bintools/extractor.py", line 65, in extract_styles
result = subprocess.run(export_args, stdout=subprocess.PIPE, creationflags=CREATE_NO_WINDOW)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 423, in run
with Popen(*popenargs, **kwargs) as process:
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 657, in __init__
raise ValueError("creationflags is only supported on Windows "
ValueError: creationflags is only supported on Windows platforms

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/grasprak287/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/qgis_plugin/algorithms.py", line 208, in processAlgorithm
raw_symbols = Extractor.extract_styles(input_file, symbol_type, mdbtools_path=mdbtools_folder)
File "/Users/grasprak287/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/bintools/extractor.py", line 67, in extract_styles
result = subprocess.run(export_args, stdout=subprocess.PIPE)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 423, in run
with Popen(*popenargs, **kwargs) as process:
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 729, in __init__
restore_signals, start_new_session)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1364, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mdb-export': 'mdb-export'

Execution failed after 0.05 seconds

**Comment by nyalldawson** [comment]
Ok - so this error is being thrown because the plugin can't find the mdb-export command. Can you please verify that this tool exists if you run it directly from a command line? Otherwise you'll need to double check the mdb tools path setup in the Processing configuration for the plugin.
