### ISSUE TITLE
SVG from font creation  -  Divide by zero error

### ISSUE THREAD

**Issue by ArrEssJay** [nyalldawson/slyr#96]
Turn on render fonts as SVG. In ESRI default style 'CADD GIS Center SDS 200.Style'

```
626/787: airfield_light_point ROTATING
Traceback (most recent call last):
File "/Users/rob/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/qgis_plugin/algorithms.py", line 283, in processAlgorithm
qgis_symbol = Symbol_to_QgsSymbol(symbol, context)
File "/Users/rob/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/converters/qgis.py", line 1016, in Symbol_to_QgsSymbol
add_symbol_layers(out, symbol, context)
File "/Users/rob/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/converters/qgis.py", line 945, in add_symbol_layers
append_SymbolLayer_to_QgsSymbolLayer(out, l, context)
File "/Users/rob/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/converters/qgis.py", line 928, in append_SymbolLayer_to_QgsSymbolLayer
append_MarkerSymbolLayer(symbol, layer, context)
File "/Users/rob/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/converters/qgis.py", line 911, in append_MarkerSymbolLayer
append_CharacterMarkerSymbolLayer(symbol, layer, context)
File "/Users/rob/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/converters/qgis.py", line 720, in append_CharacterMarkerSymbolLayer
append_CharacterMarkerSymbolLayerAsSvg(symbol, layer, context)
File "/Users/rob/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/slyr/converters/qgis.py", line 748, in append_CharacterMarkerSymbolLayerAsSvg
scale = rect.width() / font_bounding_rect.width()
ZeroDivisionError: float division by zero
```

Works ok if keeping the symbol as a font marker.

**Comment by nyalldawson** [comment]
I'm unable to locate that particular .style library. Is it part of a default ArcGIS install? I can find a version with the .serverstyle extension, but that seems to be a different beast...

**Comment by Saijin-Naib** [comment]
Located here on my install:  
C:\Program Files (x86)\ArcGIS\Desktop10.7\Styles  

[CADD GIS Center SDS 200.zip](https://github.com/nyalldawson/slyr/files/4003251/CADD.GIS.Center.SDS.200.zip)

**Comment by nyalldawson** [comment]
I've tested and there's no issue in the full version of the tool.
